# Generated by Django 4.2.3 on 2023-08-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='get_access_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
