# Generated by Django 4.2.3 on 2023-08-16 11:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_userdata_get_access_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='rooms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=11), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='userdata',
            name='old_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=13), blank=True, null=True, size=None),
        ),
    ]
