# Generated by Django 4.2.3 on 2023-08-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_remove_userdata_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
    ]
