# Generated by Django 4.2.3 on 2023-08-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_alter_userdata_number_alter_userdata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='type',
            field=models.CharField(blank=True, choices=[('worker', 'Worker'), ('tenant', 'Tenant'), ('organization', 'Organization')], max_length=25, null=True),
        ),
    ]
