# Generated by Django 4.2.3 on 2023-08-15 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_alter_userdata_first_name_alter_userdata_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название организации')),
                ('bank_details', models.JSONField(blank=True, null=True, verbose_name='Список банковских реквизитов')),
                ('address', models.TextField(verbose_name='Юридический адрес компании')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userdata',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Дополнительная пользовательская электронная почта'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий к пользователю'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='phones',
            field=models.JSONField(blank=True, null=True, verbose_name='Список телефонных номеров'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Пользовательская электронная почта'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Номер лицевого счёта'),
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateTimeField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гражданство')),
                ('military', models.CharField(blank=True, max_length=255, null=True, verbose_name='Воинская обязанность')),
                ('place_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место рождения')),
                ('position', models.CharField(max_length=75, verbose_name='Должность')),
                ('department', models.CharField(max_length=75, verbose_name='Отдел')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='authorization.organizationprofile', verbose_name='Компания, в которой работает сотрудник')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birth_date', models.DateTimeField(verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Гражданство')),
                ('military', models.CharField(blank=True, max_length=255, null=True, verbose_name='Воинская обязанность')),
                ('place_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место рождения')),
                ('snils', models.CharField(blank=True, max_length=14, null=True)),
                ('gis_uid', models.CharField(blank=True, max_length=10, null=True, verbose_name='Единый лицевой счет')),
                ('hcs_uid', models.CharField(blank=True, max_length=10, null=True, verbose_name='Идентификатор ЖКУ')),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('coop_member_date_from', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата принятия в члены ТСЖ/ЖСК')),
                ('news_count_read', models.IntegerField(default=0, verbose_name='Количество прочитанных новостей')),
                ('delivery_disabled', models.BooleanField(default=False, verbose_name='Отключено ли получение рассылки')),
                ('disable_paper_bills', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='authorization.organizationprofile', verbose_name='Организация, предоставившая доступ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='organization_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
